In [ ]:
# 提取位置编码

import numpy as np

action = [6.426e-1, -2.180e-1, 9.110e-2, -6.169e-5, 9.850e-1, 4.307e-4, 1.727e-1, 1.000e+0]
target_qpos_list = []
target_qpos_list.append(action)
target_qpos_list.append(action)
target_qpos_list.append(action)
target_qpos_list.append(action)

print(np.shape(target_qpos_list))

position = target_qpos_list[3][:7]

# 在这个位置周围随机生成一个点
print(position)

# 根据elem的数量级决定 随机加减数量

# 又机器人模型决定单个步骤是否完成

for i in range(10):
  position = [elem *(1 + (np.random.randint(100) - 50)/1000) for elem in position]
  print(position)



In [ ]:
# 逻辑比较
a = True
b = True
c = False

if a and (b or c):
  print("success")
else:
  print("fail")

In [ ]:
print(10%5)

In [2]:
import numpy as np
aaa = np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])


# bbb = np.expand_dims(aaa,3).repeat(3,axis=3)

# 三种维度的距离？？统一维度有一点浪费存储空间
# bbb = np.expand_dims(aaa,3)

aaa = aaa/30
print(np.shape(aaa))

bbb1 = np.clip((aaa * 255. * 1.0), 0, 255).astype(np.uint8)
bbb2 = np.clip((aaa * 255. * 5.0), 0, 255).astype(np.uint8)
bbb3 = np.clip((aaa * 255. * 10.0 ), 0, 255).astype(np.uint8)

ccc = np.stack((bbb1,bbb2),axis=3)
print(np.shape(ccc))
bbb4 = np.expand_dims(bbb3,axis=3)
ccc = np.append(ccc,bbb4,axis=3)
print(np.shape(ccc))
ddd = np.append(ccc,bbb4,axis=3)
print(np.shape(ddd))
# print(ccc)
# bbb = np.append(aaa,aaa)

# print(np.shape(bbb))

# print(ccc)


(5, 4, 3)
(5, 4, 3, 2)
(5, 4, 3, 3)
(5, 4, 3, 4)


In [ ]:
# 三原色 降为压缩
import numpy as np

rgb = np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])

print(np.shape(rgb))

# red = rgb[:,:,0]

# color = np.sum(rgb,2)
# color = [rgb[0]+rgb[1], rgb[1]+rgb[2]]

print(np.shape(red))
print(red)



In [4]:
ext = "oepn,steps(5)"
if len(ext) > 0 and 'steps(' in ext:
  start_of_bracket = ext.index('steps(') + 6
  steps_len = ext[start_of_bracket] 
  print(steps_len)

5


In [7]:
num_epoch = 10
for i in range(0, num_epoch):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [22]:
ext = "close_gripper();ignore_collisions;steps(3);close_gripper();"
if len(ext) > 0 and 'steps(' in ext:
  left = ext.index('steps(')+6
  right = ext[left:].index(')')
  
  print(ext[left:left+right])
  

3


In [2]:
cam_names = [['wrist'], ['wrist', 'head']] 
print(cam_names[0])

['wrist']


In [7]:
policy = {
        'num_epochs': 111
    }
config = {
        'num_epochs': 111,
        'policy': policy
    }
config['num_epochs']=222
config['policy']['num_epochs']=1112
print(config)

{'num_epochs': 222, 'policy': {'num_epochs': 1112}}


In [2]:
task_steps = ['sorting_program21', 'sorting_program22']
print(len(task_steps))

2


In [2]:
x = 1 

print(f'x={x}')

def function(x):
  x = x + 1
  print(f'x={x}')

function(x)
print(x)

x=1
x=2
1


In [7]:
import numpy as np
conmmand_len = 2
dict = {}

for i in range(1, 2*conmmand_len, 2):
  print(i+1)
  dict[f"the {i}"] = i
  print(dict)
  
  # print(np.random.randint(3))

2
{'the 1': 1}
4
{'the 1': 1, 'the 3': 3}


In [19]:
# import string

ssss = ""
num_len = 4
# ssss = [(ssss + str(i) ) for i in range(1, num_len)]
# print(ssss)

for i in range(1,num_len):
  ssss = ssss + str(i)
  
  print(type(int(ssss)),ssss)
  


<class 'int'> 1
<class 'int'> 12
<class 'int'> 123


In [15]:
import os

# os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "/home/boxjod/Gym/RLBench/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04"
# os.environ['LD_LIBRARY_PATH'] = "$COPPELIASIM_ROOT:$LD_LIBRARY_PATH"
# os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "$COPPELIASIM_ROOT"

# x = 99

# print(x.isalnum())

color_name = 'red'

print('put the %s target to the %s box' % (color_name ,color_name) )



put the red target to the red box


In [114]:
# 历史记录当中有空的，这样处理
import numpy as np
num_queries = 10

pos_initial = np.array([[0,0,0,0,0,0,0,0]])

for idx in range(1,5):
  pos_initial = np.append(pos_initial,[[idx,idx,idx,idx,idx,idx,idx,idx]], axis=0)

original_action_shape = pos_initial.shape #(32,8)  # np.zeros((32,8))
action_len = original_action_shape[0]

action_len = min(action_len, num_queries)#################

qpos_history = np.zeros((num_queries,) + original_action_shape[1:], dtype=np.float32)

pos_initial = pos_initial[::-1]

qpos_history[:action_len] = pos_initial[:action_len]

print(qpos_history)
index_refresh = 0

# eval 的时候新的history

[[4. 4. 4. 4. 4. 4. 4. 4.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [87]:
# 往前面加
index_refresh = index_refresh + 1
action = np.array([index_refresh,2,2,2,2,2,2,2])
qpos_history = np.insert(qpos_history,0,action, axis=0)[:num_queries]

# qpos_history = np.append(qpos_history[1:], action, axis=0)

print(qpos_history)

[[12.  2.  2.  2.  2.  2.  2.  2.]
 [11.  2.  2.  2.  2.  2.  2.  2.]
 [10.  2.  2.  2.  2.  2.  2.  2.]
 [ 9.  2.  2.  2.  2.  2.  2.  2.]
 [ 8.  2.  2.  2.  2.  2.  2.  2.]
 [ 7.  2.  2.  2.  2.  2.  2.  2.]
 [ 6.  2.  2.  2.  2.  2.  2.  2.]
 [ 5.  2.  2.  2.  2.  2.  2.  2.]
 [ 4.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  2.  2.  2.  2.  2.  2.  2.]]


In [94]:
end_ts = 32
start_ts = 17
num_queries = 10

root = dict()
root['/action'] = [1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2]

action_len = end_ts - start_ts + 1 
print(action_len)
if action_len < num_queries:
    action = root['/action'][start_ts : end_ts + 1]
else:
    action = root['/action'][start_ts : start_ts + num_queries]

print(len(action))
print(action)

16
10
[8, 9, 0, 1, 2, 3, 4, 5, 6, 7]


In [102]:
end_ts = 32
start_ts = 16
num_queries = 10

root = dict()
root['/action'] = [1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,0,1,2]

history_action_len = start_ts + 1
print(action_len)
print()

if history_action_len < num_queries:
    history_action = root['/action'][0 : start_ts + 1]
    for history_idx in range(start_ts + 1):
        print(history_idx)
else:
    history_action = root['/action'][start_ts - num_queries : start_ts]
    for history_idx in range(start_ts - num_queries, start_ts + 1):
        print(history_idx)

print(history_action)

16

6
7
8
9
10
11
12
13
14
15
16
[7, 8, 9, 0, 1, 2, 3, 4, 5, 6]


In [26]:
# 往后面加
index_refresh = index_refresh + 1
action = np.array([[index_refresh,2,2,2,2,2,2,2]])
qpos_history = np.append(qpos_history[1:], action, axis=0)
print(qpos_history)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [17]:
import torch

action = np.array([1,2,3,4,5,6,7,8])
print(f"{action=}")

action = torch.from_numpy(action).float()
print(f"{action=}")

history_action_embed = torch.unsqueeze(action, axis=0).repeat(1, 1,1)
print(f"{history_action_embed=}")

action=array([1, 2, 3, 4, 5, 6, 7, 8])
action=tensor([1., 2., 3., 4., 5., 6., 7., 8.])
history_action_embed=tensor([[[1., 2., 3., 4., 5., 6., 7., 8.]]])


In [104]:
import numpy as np
# 模拟图像 数据集
image_data = {
        '/observations/images/wrist': [],
    }
# image_data['wrist'] = np.ones([120,160])

image = np.ones([120,160,3])

for idx in range(32):
  image_data['/observations/images/wrist'].append(image)

# print(np.shape(image_data))
# print(image_data['/observations/images/wrist'][0])



In [105]:
# history_action
start_ts = 17
history_action_len = start_ts + 1
max_len = 32

camera_names = ['wrist']
dataset_dir = "sawyer"

# 加入历史图像
history_images = []
history_image_dict = dict()
for history_idx in range(start_ts + 1):
    
    for cam_name in camera_names:
        history_image_dict[cam_name] = image_data[f'/observations/images/{cam_name}'][history_idx]
    
    # history_images = history_images.append(history_image_dict)
    # 两个数据类型不一样的时候会出现AttributeError: 'NoneType' object has no attribute 'append'
    history_images.append(history_image_dict) # 直接这样使用append才是正确的
    
# print(f"{np.shape(history_images[0])=}")
# print(history_images[0]['wrist'])

In [106]:

history_all_cam_images = []
for history_idx in range(history_action_len):
    all_history_cam_images = []
    
    for cam_name in camera_names: 
        all_history_cam_images.append(history_images[history_idx][cam_name])

    all_history_cam_images = np.stack(all_history_cam_images, axis=0)
    
    history_all_cam_images.append(all_history_cam_images)
    
print(np.shape(all_history_cam_images))
print(np.shape(history_all_cam_images))

(1, 120, 160, 3)
(18, 1, 120, 160, 3)


In [113]:
# 这里输出要 padded 到32，不够的图像补充0

pos_initial = np.array([[9,9,9,9,9,9,9,9], [9,9,9,9,9,9,9,9], [9,9,9,9,9,9,9,9], [9,9,9,9,9,9,9,9], ])

original_action_shape = pos_initial.shape #(32,8)  # np.zeros((32,8))
action_len = original_action_shape[0]
print(original_action_shape)

history_action_len = 10

original_images_shape = np.shape(history_all_cam_images)
padded_history_images = np.zeros((history_action_len,) + original_images_shape[1:], dtype=np.float32)

padded_history_images = padded_history_images[::-1]

padded_history_images[:history_action_len] = history_all_cam_images[:history_action_len] # 往前面添加historyaction

print(np.shape(padded_history_images))

(4, 8)
(10, 1, 120, 160, 3)


In [115]:
ispad = np.zeros(90)
ispad = torch.from_numpy(ispad)
bs = 1
print(ispad.shape)
ispad = torch.unsqueeze(ispad, axis=0).repeat(bs, 1) # (1, 90)
print(ispad.shape)
ispad = ispad[:,]
print(ispad.shape)


torch.Size([90])
torch.Size([1, 90])
torch.Size([1, 90])


In [44]:
import torch
# Constructing the observations
history_all_cam_images = np.array(history_all_cam_images)
print(np.shape(history_all_cam_images))

# for history_idx in range(history_action_len):

history_images_data = torch.from_numpy(history_all_cam_images)
history_images_data = torch.einsum('q k h w c -> q k c h w', history_images_data) # 多一个querry，chunking的队列长度

print(np.shape(history_images_data))

# print(history_images_data)

# 然后返回出去，传到模型里面，在处理history_action的时候一起处理了，使用同一个backbone处理

(18, 1, 120, 160, 3)
torch.Size([18, 1, 3, 120, 160])


In [45]:
# policy
num_queries = 10


is_training = True
# train
# history_images = history_images[:, :num_queries] # 前面那个是batch_size


# eval
if not is_training:
  print(np.shape(history_images_data))
  history_images = history_images_data[:num_queries]
  print(np.shape(history_images))

torch.Size([18, 1, 3, 120, 160])
torch.Size([10, 1, 3, 120, 160])


In [46]:
# 训练的时候：
# 有batch_size

# 又要扩一个维度的batch_size，训练模式的时候有自动的 batch_size
if not is_training:
  bs = 1
  history_images = torch.unsqueeze(history_images, axis=0).repeat(bs, 1, 1, 1, 1, 1)
  

In [48]:
print(np.shape(history_images))


torch.Size([8, 10, 1, 3, 120, 160])


In [ ]:
# 输入进来的是 history_images， additional_all_history_cam_pos（num_queries，hidden_dim）

# 使用backbone处理
history_all_cam_src = []
history_all_cam_pos = []

for history_idx in range(history_action_len):
  all_history_cam_features = []
  all_history_cam_pos = []
  for cam_id, cam_name in enumerate(self.camera_names): # 0 ‘wrist’
    features, pos = self.backbones[cam_id](history_images[:,history_idx, cam_id]) # [batch_size, history_idx, cam_id, chanel, width, height]
    features = features[0] # take the last layer feature [8, 1536, 4, 5]
    pos = pos[0] # take the last layer pos [8, 1536, 4, 5]
    all_history_cam_features.append(self.input_proj(features)) # 训练的时候[8, 1536, 4, 5] -> [8, 512, 4, 5] -> [1, 8, 512, 4, 5]
    all_history_cam_pos.append(pos)  # pos的 shape 本来就是 512
      
  # fold camera dimension into width dimension
  all_history_cam_src = torch.cat(all_history_cam_features, axis=3)  # [1, 8, 512, 4, 5] -> [8, 512, 4, 5], 把多张图片折叠到了 width 维度
  all_history_cam_pos = torch.cat(all_history_cam_pos, axis=3) # [1, 8, 512, 4, 5] -> [8, 512, 4, 5] 把多张图片折叠到了 width 维度
  
  # 如何处理成Transformer Encoder的输入格式
  bs, c, h, w = all_history_cam_src.shape
  all_history_cam_src = all_history_cam_src.flatten(2).permute(2, 0, 1) # (seq*2 ,bs )
  all_history_cam_pos = all_history_cam_pos.flatten(2).permute(2, 0, 1).repeat(1, bs, 1) # 图像的编码，有几个图像就加了几个的，不用管它
  
  
  
  

  # query_embed 是一个权重 self.query_embed.weight
  # 这个 history_action 有
  
  query_embed = query_embed.unsqueeze(1).repeat(1, bs, 1)
  
  # mask = mask.flatten(1)
  additional_pos_embed = additional_pos_embed.unsqueeze(1).repeat(1, bs, 1) # seq, bs, dim 
  pos_embed = torch.cat([additional_pos_embed, pos_embed], axis=0)
  
  addition_input = torch.stack([latent_input, proprio_input_qpos, command_embedding], axis=0)
  src = torch.cat([addition_input, src], axis=0)
  
  self.encoder(src, src_key_padding_mask=mask, pos=pos_embed)
  
  
  
  
  
  
  
  history_all_cam_src.append(all_history_cam_src) #  [1, 8, 512, 4, 5]
  history_all_cam_pos.append(all_history_cam_pos)


# 然后获得了
# history_all_cam_src = ()
# history_all_cam_pos = ()





# 图像特征、图像特征位置编码、风格变量Z、joints映射后的，以及position embeddings (fixed)，权重丢进去，在训练的时候训练好的？？
hs = self.transformer(src, None, self.query_embed.weight, pos, latent_input, proprio_input_qpos, proprio_input_gpos, self.additional_pos_embed.weight, command_embedding=command_embedding_to_append)[0]





In [2]:
import torch.nn as nn
import torch

batch_size = 8
all_history_cam_src = torch.randn(batch_size, 512, 4, 5)
print(all_history_cam_src.shape)


all_history_cam_src = all_history_cam_src.flatten(2) # (bs, 512, 4, 5) -> 4x5=20 (bs, 512, 20)
all_history_cam_src = torch.mean(all_history_cam_src, dim=2).unsqueeze(1)# (bs, 512, 20) -> (bs, 512)

print(all_history_cam_src.shape)

# history_all_cam_src = torch.empty( dtype=torch.float32)
# history_all_cam_src = torch.cat([all_history_cam_src, all_history_cam_src], axis=1)

for ids in range(10):
  history_all_cam_src = torch.cat([all_history_cam_src, all_history_cam_src], axis=1)
  
print(history_all_cam_src.shape)


torch.Size([8, 512, 4, 5])
torch.Size([8, 1, 512])
torch.Size([8, 2, 512])


In [1]:
import torch

# 初始化三个 tensor
A=torch.ones(2,3)    #2x3的张量（矩阵）                                     
# tensor([[ 1.,  1.,  1.],
#         [ 1.,  1.,  1.]])
B=2*torch.ones(4,3)  #4x3的张量（矩阵）                                    
# tensor([[ 2.,  2.,  2.],
#         [ 2.,  2.,  2.],
#         [ 2.,  2.,  2.],
#         [ 2.,  2.,  2.]])
# D=2*torch.ones(2,4)	 # 2x4的张量（矩阵）
# tensor([[ 2.,  2.,  2., 2.],
#         [ 2.,  2.,  2., 2.],


# 按维数0（行）拼接 A 和 B
C=torch.cat((A,B),0) 
# tensor([[ 1.,  1.,  1.],
#          [ 1.,  1.,  1.],
#          [ 2.,  2.,  2.],
#          [ 2.,  2.,  2.],
#          [ 2.,  2.,  2.],
#          [ 2.,  2.,  2.]])
print(C.shape)
# torch.Size([6, 3])

torch.Size([6, 3])


In [6]:
import numpy as np

max_timesteps = 32
hidden_dim = 512
history_image_feature = np.zeros((max_timesteps,) + (hidden_dim,), dtype=np.float32)

print(f"{np.shape(history_image_feature)=}")


np.shape(history_image_feature)=(32, 512)


In [153]:
import torch
max_timesteps = 10
hidden_dim = 512

image_src = torch.rand(1,512)
# print(image_src)
image_pos = torch.rand(1,512)

encode_history_image_pos = [image_src, image_pos]

print(np.shape(encode_history_image_pos[0]))
history_image_feature = np.zeros((2,max_timesteps) + (512,), dtype=np.float32)

print(np.shape(history_image_feature[:,0]))


torch.Size([1, 512])
(2, 512)


In [163]:
history_image_feature[0] = np.insert(history_image_feature[0], 0, encode_history_image_pos[0], axis=0)[:max_timesteps]
history_image_feature[1] = np.insert(history_image_feature[1], 0, encode_history_image_pos[1], axis=0)[:max_timesteps]

print(np.shape(history_image_feature))
for idx in range(max_timesteps):
  print(history_image_feature[0][idx][0])
for idx in range(max_timesteps):
  print(history_image_feature[1][idx][0])


(2, 10, 512)
0.84650916
0.84650916
0.84650916
0.84650916
0.84650916
0.84650916
0.84650916
0.84650916
0.84650916
0.84650916
0.5960442
0.5960442
0.5960442
0.5960442
0.5960442
0.5960442
0.5960442
0.5960442
0.5960442
0.5960442
