In [ ]:
# 提取位置编码

import numpy as np

action = [6.426e-1, -2.180e-1, 9.110e-2, -6.169e-5, 9.850e-1, 4.307e-4, 1.727e-1, 1.000e+0]
target_qpos_list = []
target_qpos_list.append(action)
target_qpos_list.append(action)
target_qpos_list.append(action)
target_qpos_list.append(action)

print(np.shape(target_qpos_list))

position = target_qpos_list[3][:7]

# 在这个位置周围随机生成一个点
print(position)

# 根据elem的数量级决定 随机加减数量

# 又机器人模型决定单个步骤是否完成

for i in range(10):
  position = [elem *(1 + (np.random.randint(100) - 50)/1000) for elem in position]
  print(position)



In [ ]:
# 逻辑比较
a = True
b = True
c = False

if a and (b or c):
  print("success")
else:
  print("fail")

In [ ]:
print(10%5)

In [12]:
import numpy as np
aaa = np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])

# print(aaa)

# bbb = np.expand_dims(aaa,3).repeat(3,axis=3)

# 三种维度的距离？？统一维度有一点浪费存储空间
# bbb = np.expand_dims(aaa,3)

aaa = aaa/30
bbb1 = np.clip((aaa * 255. * 1.0), 0, 255).astype(np.uint8)
bbb2 = np.clip((aaa * 255. * 5.0), 0, 255).astype(np.uint8)
bbb3 = np.clip((aaa * 255. * 10.0 ), 0, 255).astype(np.uint8)

ccc = np.stack((bbb1,bbb2,bbb3),axis=3)

# bbb = np.append(aaa,aaa)
print(np.shape(aaa))
# print(np.shape(bbb))
print(np.shape(ccc))
print(ccc)



(5, 4, 3)
(5, 4, 3, 3)
[[[[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]]


 [[[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]]


 [[[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]]


 [[[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]]


 [[[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85]
   [ 17  85 170]
   [ 25 127 255]]

  [[  8  42  85

In [11]:
# 三原色 降为压缩
import numpy as np

rgb = np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])

print(np.shape(rgb))

# red = rgb[:,:,0]

# color = np.sum(rgb,2)
# color = [rgb[0]+rgb[1], rgb[1]+rgb[2]]

print(np.shape(red))
print(red)



(5, 4, 3)
(5, 4)
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
