In [ ]:
# 提取位置编码

import numpy as np

action = [6.426e-1, -2.180e-1, 9.110e-2, -6.169e-5, 9.850e-1, 4.307e-4, 1.727e-1, 1.000e+0]
target_qpos_list = []
target_qpos_list.append(action)
target_qpos_list.append(action)
target_qpos_list.append(action)
target_qpos_list.append(action)

print(np.shape(target_qpos_list))

position = target_qpos_list[3][:7]

# 在这个位置周围随机生成一个点
print(position)

# 根据elem的数量级决定 随机加减数量

# 又机器人模型决定单个步骤是否完成

for i in range(10):
  position = [elem *(1 + (np.random.randint(100) - 50)/1000) for elem in position]
  print(position)



In [ ]:
# 逻辑比较
a = True
b = True
c = False

if a and (b or c):
  print("success")
else:
  print("fail")

In [ ]:
print(10%5)

In [2]:
import numpy as np
aaa = np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])


# bbb = np.expand_dims(aaa,3).repeat(3,axis=3)

# 三种维度的距离？？统一维度有一点浪费存储空间
# bbb = np.expand_dims(aaa,3)

aaa = aaa/30
print(np.shape(aaa))

bbb1 = np.clip((aaa * 255. * 1.0), 0, 255).astype(np.uint8)
bbb2 = np.clip((aaa * 255. * 5.0), 0, 255).astype(np.uint8)
bbb3 = np.clip((aaa * 255. * 10.0 ), 0, 255).astype(np.uint8)

ccc = np.stack((bbb1,bbb2),axis=3)
print(np.shape(ccc))
bbb4 = np.expand_dims(bbb3,axis=3)
ccc = np.append(ccc,bbb4,axis=3)
print(np.shape(ccc))
ddd = np.append(ccc,bbb4,axis=3)
print(np.shape(ddd))
# print(ccc)
# bbb = np.append(aaa,aaa)

# print(np.shape(bbb))

# print(ccc)


(5, 4, 3)
(5, 4, 3, 2)
(5, 4, 3, 3)
(5, 4, 3, 4)


In [ ]:
# 三原色 降为压缩
import numpy as np

rgb = np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])

print(np.shape(rgb))

# red = rgb[:,:,0]

# color = np.sum(rgb,2)
# color = [rgb[0]+rgb[1], rgb[1]+rgb[2]]

print(np.shape(red))
print(red)



In [4]:
ext = "oepn,steps(5)"
if len(ext) > 0 and 'steps(' in ext:
  start_of_bracket = ext.index('steps(') + 6
  steps_len = ext[start_of_bracket] 
  print(steps_len)

5


In [7]:
num_epoch = 10
for i in range(0, num_epoch):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [22]:
ext = "close_gripper();ignore_collisions;steps(3);close_gripper();"
if len(ext) > 0 and 'steps(' in ext:
  left = ext.index('steps(')+6
  right = ext[left:].index(')')
  
  print(ext[left:left+right])
  

3


In [2]:
cam_names = [['wrist'], ['wrist', 'head']] 
print(cam_names[0])

['wrist']


In [7]:
policy = {
        'num_epochs': 111
    }
config = {
        'num_epochs': 111,
        'policy': policy
    }
config['num_epochs']=222
config['policy']['num_epochs']=1112
print(config)

{'num_epochs': 222, 'policy': {'num_epochs': 1112}}


In [2]:
task_steps = ['sorting_program21', 'sorting_program22']
print(len(task_steps))

2


In [2]:
x = 1 

print(f'x={x}')

def function(x):
  x = x + 1
  print(f'x={x}')

function(x)
print(x)

x=1
x=2
1


In [7]:
import numpy as np
conmmand_len = 2
dict = {}

for i in range(1, 2*conmmand_len, 2):
  print(i+1)
  dict[f"the {i}"] = i
  print(dict)
  
  # print(np.random.randint(3))

2
{'the 1': 1}
4
{'the 1': 1, 'the 3': 3}


In [19]:
# import string

ssss = ""
num_len = 4
# ssss = [(ssss + str(i) ) for i in range(1, num_len)]
# print(ssss)

for i in range(1,num_len):
  ssss = ssss + str(i)
  
  print(type(int(ssss)),ssss)
  


<class 'int'> 1
<class 'int'> 12
<class 'int'> 123


In [15]:
import os

# os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "/home/boxjod/Gym/RLBench/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04"
# os.environ['LD_LIBRARY_PATH'] = "$COPPELIASIM_ROOT:$LD_LIBRARY_PATH"
# os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "$COPPELIASIM_ROOT"

# x = 99

# print(x.isalnum())

color_name = 'red'

print('put the %s target to the %s box' % (color_name ,color_name) )



put the red target to the red box


In [44]:
# 历史记录当中有空的，这样处理
import numpy as np
num_queries = 15

pos_initial = np.array([[9,9,9,9,9,9,9,9], [9,9,9,9,9,9,9,9], [9,9,9,9,9,9,9,9], [9,9,9,9,9,9,9,9], ])

original_action_shape = pos_initial.shape #(32,8)  # np.zeros((32,8))
action_len = original_action_shape[0]
print(original_action_shape)

qpos_history = np.zeros((num_queries,) + (8,), dtype=np.float32)

qpos_history[-action_len:] = pos_initial

print(qpos_history)
index_refresh = 0

(4, 8)
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [9. 9. 9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9. 9. 9.]]


In [62]:
# 往前面加
index_refresh = index_refresh + 1
action = np.array([index_refresh,2,2,2,2,2,2,2])
qpos_history = np.insert(qpos_history,0,action, axis=0)[:15]

# qpos_history = np.append(qpos_history[1:], action, axis=0)

print(qpos_history)

[[17.  2.  2.  2.  2.  2.  2.  2.]
 [16.  2.  2.  2.  2.  2.  2.  2.]
 [15.  2.  2.  2.  2.  2.  2.  2.]
 [14.  2.  2.  2.  2.  2.  2.  2.]
 [13.  2.  2.  2.  2.  2.  2.  2.]
 [12.  2.  2.  2.  2.  2.  2.  2.]
 [11.  2.  2.  2.  2.  2.  2.  2.]
 [10.  2.  2.  2.  2.  2.  2.  2.]
 [ 9.  2.  2.  2.  2.  2.  2.  2.]
 [ 8.  2.  2.  2.  2.  2.  2.  2.]
 [ 7.  2.  2.  2.  2.  2.  2.  2.]
 [ 6.  2.  2.  2.  2.  2.  2.  2.]
 [ 5.  2.  2.  2.  2.  2.  2.  2.]
 [ 4.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  2.  2.  2.  2.  2.  2.  2.]]


In [26]:
# 往后面加
index_refresh = index_refresh + 1
action = np.array([[index_refresh,2,2,2,2,2,2,2]])
qpos_history = np.append(qpos_history[1:], action, axis=0)
print(qpos_history)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [17]:
import torch

action = np.array([1,2,3,4,5,6,7,8])
print(f"{action=}")

action = torch.from_numpy(action).float()
print(f"{action=}")

history_action_embed = torch.unsqueeze(action, axis=0).repeat(1, 1,1)
print(f"{history_action_embed=}")

action=array([1, 2, 3, 4, 5, 6, 7, 8])
action=tensor([1., 2., 3., 4., 5., 6., 7., 8.])
history_action_embed=tensor([[[1., 2., 3., 4., 5., 6., 7., 8.]]])


In [18]:
min(num_queries, 2)

2